import {
  Activity,
  AppWindow,
  Binary,
  BriefcaseBusiness,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  Clock3,
  Cpu,
  FileClock,
  FileSpreadsheet,
  FolderKanban,
  FolderOpen,
  Fingerprint,
  Gauge,
  Group,
  House,
  Lightbulb,
  ListChecks,
  MapPin,
  MonitorCog,
  ScanSearch,
  Settings,
  TimerReset,
  TrendingUp,
  Users,
  UserRound,
  Waypoints,
  Workflow,
  Highlighter,
  Bell,
} from "lucide-react"

export const dashboardNavigation = [
  {
    title: "Home",
    url: "/dashboard",
    icon: House,
  },
  {
    title: "Timesheets",
    url: "/dashboard/timesheets",
    icon: Clock3,
    items: [
      { title: "View & Edit", url: "/dashboard/timesheets/view-edit", icon: Binary },
      { title: "Approvals", url: "/dashboard/timesheets/approvals", icon: FileClock },
    ],
  },
  {
    title: "Attendance",
    url: "/dashboard/attendance",
    icon: CalendarCheck2,
    items: [
      { title: "Dashboard", url: "/dashboard/attendance", icon: Gauge },
      { title: "Attendance List", url: "/dashboard/attendance/list", icon: ListChecks },
      { title: "Locations", url: "/dashboard/attendance/locations", icon: MapPin },
      { title: "Devices", url: "/dashboard/attendance/devices", icon: Cpu },
    ],
  },
  {
    title: "Activity",
    url: "/dashboard/activity",
    icon: Activity,
    items: [
      { title: "Screenshots", url: "/dashboard/activity/screenshots", icon: ScanSearch },
      { title: "Apps", url: "/dashboard/activity/apps", icon: AppWindow },
      { title: "URLs", url: "/dashboard/activity/urls", icon: Waypoints },
    ],
  },
  {
    title: "Insight",
    url: "/dashboard/insight",
    icon: Lightbulb,
    items: [
      { title: "Highlights", url: "/dashboard/insight/highlights", icon: Highlighter },
      { title: "Performance", url: "/dashboard/insight/performance", icon: TrendingUp },
      { title: "Timeline", url: "/dashboard/insight/timeline", icon: TimerReset },
      { title: "Unusual Activity", url: "/dashboard/insight/unusual-activity", icon: Activity },
      { title: "Smart Notification", url: "/dashboard/insight/smart-notification", icon: Bell },
    ],
  },
  {
    title: "Schedules",
    url: "/dashboard/schedules",
    icon: CalendarDays,
    items: [
      { title: "Work Schedules", url: "/dashboard/schedules/work-schedules", icon: CalendarDays },
      { title: "Member Schedules", url: "/dashboard/schedules/member-schedules", icon: UserRound },
    ],
  },
  {
    title: "Project management",
    url: "/dashboard/project-management",
    icon: FolderKanban,
    items: [
      { title: "Projects", url: "/dashboard/project-management/projects", icon: FolderOpen },
      { title: "Teams", url: "/dashboard/project-management/teams", icon: Users },
      { title: "Clients", url: "/dashboard/project-management/clients", icon: BriefcaseBusiness },
    ],
  },
  {
    title: "Shift",
    url: "/dashboard/shift",
    icon: CalendarClock,
    items: [
      { title: "Shift Management", url: "/dashboard/shift/management", icon: CalendarClock },
      { title: "Shift Assignment", url: "/dashboard/shift/assignment", icon: UserRound },
    ],
  },
  {
    title: "Reports",
    url: "/dashboard/reports",
    icon: FileSpreadsheet,
    items: [
      { title: "Time & activity", url: "/dashboard/reports/time-activity", icon: Clock3 },
      { title: "Daily totals", url: "/dashboard/reports/daily-totals", icon: CalendarDays },
      { title: "All reports", url: "/dashboard/reports/all", icon: FileSpreadsheet },
      { title: "Customized reports", url: "/dashboard/reports/customized", icon: Workflow },
    ],
  },
  {
    title: "People",
    url: "/dashboard/people",
    icon: Users,
    items: [
      { title: "Members", url: "/dashboard/people/members", icon: Users },
      { title: "Fingerprint", url: "/dashboard/people/fingerprint", icon: Fingerprint },
      { title: "Groups", url: "/dashboard/people/groups", icon: Group },
      { title: "Positions", url: "/dashboard/people/positions", icon: BriefcaseBusiness },
    ],
  },
  {
    title: "Configuration",
    url: "/dashboard/configuration/feature-settings",
    icon: Settings,
    items: [
      { title: "Feature Settings", url: "/dashboard/configuration/feature-settings", icon: Settings },
      { title: "Organization Settings", url: "/dashboard/configuration/organization-settings", icon: MonitorCog },
      { title: "Applications", url: "/dashboard/configuration/applications", icon: AppWindow },
    ],
  },
]
